name: Trigger auto deployment for colorapp

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/colorapp-AutoDeployTrigger-78d9da8b-4631-4bbe-ad15-ec0071659a18.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.COLORAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.COLORAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.COLORAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: searchapigoregistry.azurecr.io
          registryUsername: ${{ secrets.COLORAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.COLORAPP_REGISTRY_PASSWORD }}
          containerAppName: colorapp
          resourceGroup: searchAPIResourceGroup
          imageToBuild: searchapigoregistry.azurecr.io/colorapp:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


